# List of stages for jobs, and their order of execution
stages:          
  - build
  - test
  - deploy


composer:
  tags:
    - SSH
  stage: build
  script:
    - composer install
    - cp .env.example .env
    - sed -i 's/DB_DATABASE=.*/DB_DATABASE=andynews/' .env
    - sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=testdb/' .env
    - php artisan key:generate
  artifacts:
    untracked: true

test:
  tags:
    - SSH
  dependencies:
    - composer
  stage: test
  script:
    - ./vendor/bin/phpunit    

deploy:
  tags:
    - SSH
  stage: deploy
  dependencies:
    - composer
  script:
    - sudo rm -rf /var/www/laravel
    - sudo cp -r $PWD /var/www/laravel
    - sudo chown -R apache:apache /var/www/laravel
    - sudo chmod -R 755 /var/www/laravel/storage

  # SSH runner doesn't support
  # artifacts:
  #   expire_in: 1 day
  #   paths:
  #     - vendor/
  #     - .env
  
  # cache: 
  #   key: master-composer
  #   paths:
  #     - vendor/

