# List of stages for jobs, and their order of execution
stages:          
  - build
  - test
  - deploy


composer:
  tags:
    - SSH
  stage: build
  script:
    - composer install
    - cp .env.example .env
    - php artisan key:generate
  artifacts:
    untracked: true
    

deploy:
 tags:
   - SSH
 stage: deploy
 dependencies:
   - composer
 script:
   - sudo mv /var/www/laravel /var/www/laravel2
   - sudo cp -r $PWD /var/www/laravel
   - sudo chmod -R 755 /var/www/laravel/storage

  # SSH runner doesn't support
  # artifacts:
  #   expire_in: 1 day
  #   paths:
  #     - vendor/
  #     - .env
  
  # cache: 
  #   key: master-composer
  #   paths:
  #     - vendor/

