# List of stages for jobs, and their order of execution
stages:          
  - build
  - test
  - deploy


composer:
  tags:
    - SSH
  stage: build
  script:
    - composer install
  artifacts:
    untracked: true
    

deploy:
 tags:
   - SSH
 stage: deploy
 dependencies:
   - composer
 script:
   - cp .env.example .env
   - sed -e 's/DB_DATABASE=.*/DB_DATABASE=permission/' .env
   - sed -e 's/DB_PASSWORD=.*/DB_PASSWPRD=testdb/' .env
   - php artisan key:generate
   - sudo rm -rf /var/www/laravel
   - sudo cp -r $PWD /var/www/laravel
   - sudo chown -R apache:apache /var/www/laravel
   - sudo chmod -R 755 /var/www/laravel/storage

  # SSH runner doesn't support
  # artifacts:
  #   expire_in: 1 day
  #   paths:
  #     - vendor/
  #     - .env
  
  # cache: 
  #   key: master-composer
  #   paths:
  #     - vendor/

